=== LuceWCL/documents-structures/devoirs/ex1.dtd
<!ELEMENT livre (titre, auteur, version, serie, resume, personnages+, adaptation)>
<!ELEMENT titre (#PCDATA)>
<!ELEMENT auteur (nom, prenom)>
<!ELEMENT nom (#PCDATA)>
<!ELEMENT prenom (#PCDATA)>
<!ELEMENT version (date, editeur, ISBN)>
<!ATTLIST version 
          pays CDATA #REQUIRED>
<!ELEMENT date (#PCDATA)>
<!ELEMENT editeur (#PCDATA)>
<!ELEMENT ISBN (#PCDATA)>
<!ELEMENT serie (previous, following)>
<!ELEMENT previous (#PCDATA)>
<!ELEMENT following (#PCDATA)>
<!ELEMENT resume (#PCDATA)>
<!ELEMENT personnages (#PCDATA)>
<!ELEMENT adaptation (#PCDATA)>

=== LuceWCL/documents-structures/exercices/ex1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE livre SYSTEM "ex1.dtd">
<livre>
  <titre>Le Silence des agneaux</titre>
  <auteur>
    <nom>Harris</nom>
     <prenom>Thomas</prenom>
  </auteur>
  <version pays="US">
    <date>1988</date>
    <editeur>St. Martin's Press</editeur>
    <ISBN>0-312-02282-4</ISBN>
  </version>
  <serie>
    <previous>Dragon rouge</previous>
    <following>Hannibal</following>
  </serie>
  <resume></resume>
  <personnages></personnages>
  <adaptation></adaptation>
</livre>
